import type { UserConfig, Recommendation, RiskAlert } from './types';
import { generateDecisionTrace } from './trace';
import { generatePortabilityPlan } from './portability';
import { getServiceMapping } from './services';
import { analyzeLockIn } from './lockin';

export function generatePMPacket(
  config: UserConfig,
  recommendation: Recommendation,
  risks: RiskAlert[],
): string {
  const { primary, allScored } = recommendation;
  const trace = generateDecisionTrace(config, primary);
  const plan = generatePortabilityPlan(primary.platform.id);
  const lockIn = analyzeLockIn(primary.platform.id);
  const stack = getServiceMapping(primary.platform.id, config.workloadType);

  const dimLines = trace.topContributors.map(
    (c) => `| ${c.label} | ${c.score}/5 | ${c.finalWeight}x | ${c.contribution.toFixed(1)} |`,
  );

  const workloadLabels: Record<string, string> = {
    chatbot: 'Chatbot',
    rag: 'RAG Application',
    agent: 'Agent Workflow',
    multimodal: 'Multimodal AI',
    fine_tuned: 'Fine-Tuned Model',
    copilot: 'AI Copilot',
  };

  const sections: string[] = [
    '# AI Platform Decision — PM Packet',
    '',
    '## Configuration',
    '',
    `- **Workload:** ${workloadLabels[config.workloadType]}`,
    `- **Data Gravity:** ${config.dataGravity.replace(/_/g, ' ')}`,
    `- **Security:** ${config.securityLevel.replace(/_/g, ' ')}`,
    `- **Deployment:** ${config.deploymentPreference.replace(/_/g, ' ')}`,
    `- **Governance:** ${config.governanceRequirement}`,
    '',
    '## Recommendation',
    '',
    `**${primary.platform.name}** — Score: ${primary.normalizedScore}/100`,
    '',
    recommendation.explanation,
    '',
    '## Score Table (Top 5 Dimensions)',
    '',
    '| Dimension | Score | Weight | Contribution |',
    '|-----------|-------|--------|-------------|',
    ...dimLines,
    '',
    '## Platform Rankings',
    '',
    ...allScored.map(
      (s) => `${s.rank}. **${s.platform.name}** — ${s.normalizedScore}/100`,
    ),
    '',
    '## Service Mapping',
    '',
    ...Object.entries(stack).map(
      ([key, service]) =>
        `- **${key.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase())}:** ${service}`,
    ),
    '',
    '## Risks & Mitigations',
    '',
    ...risks
      .filter((r) => r.severity !== 'info')
      .map((r) => `- **${r.title}:** ${r.description}`),
    ...(risks.filter((r) => r.severity === 'info').length > 0
      ? ['', '**Info:**', ...risks.filter((r) => r.severity === 'info').map((r) => `- ${r.title}: ${r.description}`)]
      : []),
    '',
    '## Lock-in & Portability Plan',
    '',
    `**Overall Lock-in:** ${lockIn.overallLevel}`,
    '',
    ...plan.steps.map(
      (s) => `**${s.step}. ${s.title}:** ${s.recommendation}`,
    ),
    '',
    '---',
    `*Generated by AI Platform Decision Engine — ${new Date().toISOString().split('T')[0]}*`,
  ];

  return sections.join('\n');
}
